name: Build on Push

on: [push]

env:
  PYOPENGL_PLATFORM: osmesa

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Mesa
        run: | 
          sudo apt update
          sudo apt install libgl1-mesa-glx freeglut3-dev python3-opengl
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: environment
      - name: Build
        run: |
          conda info
          conda list
          mkdir outputs
          python build.py
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/