name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: environment_ci.yml
          activate-environment: environment_ci
      - name: Build
        shell: bash -l {0}
        run: |
          conda info
          conda list
          mkdir outputs
          python build.py
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/